--------------------------------------------------------
--  File created - Monday-March-13-2017   
--------------------------------------------------------

--------------------------------------------------------
--  DDL for Table ASSISTE
--------------------------------------------------------

  CREATE TABLE "TESTER"."ASSISTE" 
   (	"REF_I" NUMBER, 
	"REF_C" NUMBER, 
	"MATIERE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLASSE
--------------------------------------------------------

  CREATE TABLE "TESTER"."CLASSE" 
   (	"ID_CLASSE" NUMBER, 
	"NOMC" VARCHAR2(20 BYTE), 
	"CAPACITE" NUMBER(2,0), 
	"NIV" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ELEVE
--------------------------------------------------------

  CREATE TABLE "TESTER"."ELEVE" 
   (	"ID_ELEVE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATENAISS" DATE, 
	"LIEUNAISS" NUMBER, 
	"ADRESSE" VARCHAR2(40 BYTE), 
	"VILLE" VARCHAR2(20 BYTE), 
	"CODEP" NUMBER(4,0), 
	"SEX" CHAR(1 BYTE), 
	"REF_P" NUMBER, 
	"REF_NIV" CHAR(1 BYTE), 
	"REF_C" NUMBER(4,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"TEL" NUMBER, 
	"TEL2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INST
--------------------------------------------------------

  CREATE TABLE "TESTER"."INST" 
   (	"ID" NUMBER(2,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATENAISS" DATE, 
	"NCIN" NUMBER(8,0), 
	"DATEEMB" DATE, 
	"SEX" CHAR(1 BYTE), 
	"IMM" NUMBER, 
	"GRADE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(30 BYTE), 
	"VILLE" VARCHAR2(20 BYTE), 
	"CODEP" NUMBER(4,0), 
	"TEL" NUMBER(11,0), 
	"TEL2" NUMBER(11,0), 
	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NIVEAU
--------------------------------------------------------

  CREATE TABLE "TESTER"."NIVEAU" 
   (	"NIV" CHAR(1 BYTE), 
	"ANNEE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PARENT
--------------------------------------------------------

  CREATE TABLE "TESTER"."PARENT" 
   (	"ID_PARENT" NUMBER(4,0), 
	"NOMP" VARCHAR2(20 BYTE), 
	"PROFP" VARCHAR2(20 BYTE), 
	"NOMM" VARCHAR2(20 BYTE), 
	"PROFM" VARCHAR2(20 BYTE), 
	"TELP" VARCHAR2(11 BYTE), 
	"EMAILP" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_C
--------------------------------------------------------

   CREATE SEQUENCE  "TESTER"."SEQ_ID_C"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_E
--------------------------------------------------------

   CREATE SEQUENCE  "TESTER"."SEQ_ID_E"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 50 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_I
--------------------------------------------------------

   CREATE SEQUENCE  "TESTER"."SEQ_ID_I"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_P
--------------------------------------------------------

   CREATE SEQUENCE  "TESTER"."SEQ_ID_P"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 30 ORDER  NOCYCLE ;
REM INSERTING into TESTER.APEX$_ACL
SET DEFINE OFF;
REM INSERTING into TESTER.APEX$_WS_FILES
SET DEFINE OFF;
REM INSERTING into TESTER.APEX$_WS_HISTORY
SET DEFINE OFF;
REM INSERTING into TESTER.APEX$_WS_LINKS
SET DEFINE OFF;
REM INSERTING into TESTER.APEX$_WS_NOTES
SET DEFINE OFF;
REM INSERTING into TESTER.APEX$_WS_ROWS
SET DEFINE OFF;
REM INSERTING into TESTER.APEX$_WS_TAGS
SET DEFINE OFF;
REM INSERTING into TESTER.APEX$_WS_WEBPG_SECTIONS
SET DEFINE OFF;
REM INSERTING into TESTER.APEX$_WS_WEBPG_SECTION_HISTORY
SET DEFINE OFF;
REM INSERTING into TESTER.ASSISTE
SET DEFINE OFF;
REM INSERTING into TESTER.CLASSE
SET DEFINE OFF;
REM INSERTING into TESTER.ELEVE
SET DEFINE OFF;
REM INSERTING into TESTER.INST
SET DEFINE OFF;
REM INSERTING into TESTER.NIVEAU
SET DEFINE OFF;
REM INSERTING into TESTER.PARENT
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index PARENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTER"."PARENT_PK" ON "TESTER"."PARENT" ("ID_PARENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index ASSISTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTER"."ASSISTE_PK" ON "TESTER"."ASSISTE" ("REF_I", "REF_C", "MATIERE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index CLASSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTER"."CLASSE_PK" ON "TESTER"."CLASSE" ("ID_CLASSE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NIVEAU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTER"."NIVEAU_PK" ON "TESTER"."NIVEAU" ("NIV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index ELEVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTER"."ELEVE_PK" ON "TESTER"."ELEVE" ("ID_ELEVE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  DDL for Index INST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTER"."INST_PK" ON "TESTER"."INST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  Constraints for Table INST
--------------------------------------------------------

  ALTER TABLE "TESTER"."INST" ADD CONSTRAINT "INST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTER"."INST" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("CODEP" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("VILLE" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("IMM" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("DATEEMB" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("NCIN" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("DATENAISS" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."INST" MODIFY ("ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table NIVEAU
--------------------------------------------------------

  ALTER TABLE "TESTER"."NIVEAU" ADD CONSTRAINT "NIVEAU_PK" PRIMARY KEY ("NIV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTER"."NIVEAU" MODIFY ("ANNEE" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."NIVEAU" MODIFY ("NIV" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table PARENT
--------------------------------------------------------

  ALTER TABLE "TESTER"."PARENT" ADD CONSTRAINT "PARENT_PK" PRIMARY KEY ("ID_PARENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTER"."PARENT" MODIFY ("TELP" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."PARENT" MODIFY ("PROFM" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."PARENT" MODIFY ("NOMM" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."PARENT" MODIFY ("PROFP" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."PARENT" MODIFY ("NOMP" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."PARENT" MODIFY ("ID_PARENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASSISTE
--------------------------------------------------------

  ALTER TABLE "TESTER"."ASSISTE" ADD CONSTRAINT "ASSISTE_PK" PRIMARY KEY ("REF_I", "REF_C", "MATIERE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTER"."ASSISTE" MODIFY ("MATIERE" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ASSISTE" MODIFY ("REF_C" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ASSISTE" MODIFY ("REF_I" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table ELEVE
--------------------------------------------------------

  ALTER TABLE "TESTER"."ELEVE" ADD CONSTRAINT "ELEVE_PK" PRIMARY KEY ("ID_ELEVE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("TEL" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("REF_P" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("CODEP" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("VILLE" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("LIEUNAISS" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("DATENAISS" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."ELEVE" MODIFY ("ID_ELEVE" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table CLASSE
--------------------------------------------------------

  ALTER TABLE "TESTER"."CLASSE" ADD CONSTRAINT "CLASSE_PK" PRIMARY KEY ("ID_CLASSE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTER"."CLASSE" MODIFY ("NIV" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."CLASSE" MODIFY ("CAPACITE" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."CLASSE" MODIFY ("NOMC" NOT NULL ENABLE);
  ALTER TABLE "TESTER"."CLASSE" MODIFY ("ID_CLASSE" NOT NULL ENABLE);
  
--------------------------------------------------------
--  Ref Constraints for Table ASSISTE
--------------------------------------------------------

  ALTER TABLE "TESTER"."ASSISTE" ADD CONSTRAINT "ASSISTE_FK1" FOREIGN KEY ("REF_I")
	  REFERENCES "TESTER"."INST" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TESTER"."ASSISTE" ADD CONSTRAINT "ASSISTE_FK2" FOREIGN KEY ("REF_C")
	  REFERENCES "TESTER"."CLASSE" ("ID_CLASSE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLASSE
--------------------------------------------------------

  ALTER TABLE "TESTER"."CLASSE" ADD CONSTRAINT "CLASSE_FKNIV" FOREIGN KEY ("NIV")
	  REFERENCES "TESTER"."NIVEAU" ("NIV") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ELEVE
--------------------------------------------------------

  ALTER TABLE "TESTER"."ELEVE" ADD CONSTRAINT "ELEVE_FKC" FOREIGN KEY ("REF_C")
	  REFERENCES "TESTER"."CLASSE" ("ID_CLASSE") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TESTER"."ELEVE" ADD CONSTRAINT "ELEVE_FKN" FOREIGN KEY ("REF_NIV")
	  REFERENCES "TESTER"."NIVEAU" ("NIV") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TESTER"."ELEVE" ADD CONSTRAINT "ELEVE_FKP" FOREIGN KEY ("REF_P")
	  REFERENCES "TESTER"."PARENT" ("ID_PARENT") ON DELETE SET NULL ENABLE;
