--------------------------------------------------------
--  File created - Saturday-May-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ABSENCE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."ABSENCE" 
   (	"ID_ABSENCE" NUMBER(5,0), 
	"DATE_ABS" DATE, 
	"REF_SC" NUMBER, 
	"REF_E" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table APPARTIENT
--------------------------------------------------------

  CREATE TABLE "GECOLE"."APPARTIENT" 
   (	"REF_C" NUMBER, 
	"REF_E" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table APPRECIATION
--------------------------------------------------------

  CREATE TABLE "GECOLE"."APPRECIATION" 
   (	"ID_APPR" NUMBER(5,0), 
	"CONTENU" VARCHAR2(200 BYTE), 
	"REF_E" NUMBER(4,0), 
	"REF_INST" NUMBER(3,0), 
	"REF_MODULE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLASSE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."CLASSE" 
   (	"ID_CLASSE" NUMBER(3,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"CAPACITE" NUMBER(2,0), 
	"NB_ELEVES" NUMBER(2,0), 
	"REF_NIV" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ELEVE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."ELEVE" 
   (	"ID_ELEVE" NUMBER(4,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATE_NAISS" DATE, 
	"LIEU_NAISS" VARCHAR2(30 BYTE), 
	"SEX" CHAR(1 BYTE), 
	"ADRESSE" VARCHAR2(50 BYTE), 
	"VILLE" VARCHAR2(20 BYTE), 
	"CODEP" NUMBER(4,0), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"DATE_INS" DATE, 
	"REF_P" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INST
--------------------------------------------------------

  CREATE TABLE "GECOLE"."INST" 
   (	"ID_INST" NUMBER(3,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NCIN" VARCHAR2(8 BYTE), 
	"SEX" CHAR(1 BYTE), 
	"IMMATRICULE" VARCHAR2(8 BYTE), 
	"GRADE" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(40 BYTE), 
	"VILLE" VARCHAR2(20 BYTE), 
	"CODEP" NUMBER(4,0), 
	"TEL" VARCHAR2(8 BYTE), 
	"TEL2" VARCHAR2(8 BYTE), 
	"DATE_NAISS" DATE, 
	"DATE_EMB" DATE, 
	"EMAIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATIERE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."MATIERE" 
   (	"ID_MATIERE" NUMBER(4,0), 
	"NOM" VARCHAR2(40 BYTE), 
	"COEF" NUMBER(1,1), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"REF_MODULE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MODULE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."MODULE" 
   (	"ID_MODULE" NUMBER, 
	"NOM" VARCHAR2(40 BYTE), 
	"REF_NIV" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NIVEAU
--------------------------------------------------------

  CREATE TABLE "GECOLE"."NIVEAU" 
   (	"ID_NIVEAU" NUMBER(5,0), 
	"ANNEE" VARCHAR2(4 BYTE), 
	"NIV" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."NOTE" 
   (	"ID_NOTE" NUMBER(5,0), 
	"NOTE" NUMBER(2,2), 
	"TYPE" VARCHAR2(20 BYTE), 
	"REF_INST" NUMBER(3,0), 
	"REF_E" NUMBER(4,0), 
	"REF_MAT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARENT
--------------------------------------------------------

  CREATE TABLE "GECOLE"."PARENT" 
   (	"ID_PARENT" NUMBER(4,0), 
	"NOM_PERE" VARCHAR2(40 BYTE), 
	"NOM_MERE" VARCHAR2(40 BYTE), 
	"PROF_P" VARCHAR2(30 BYTE), 
	"PROF_M" VARCHAR2(30 BYTE), 
	"TEL_P" VARCHAR2(8 BYTE), 
	"EMAIL_P" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTICIPE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."PARTICIPE" 
   (	"REF_INST" NUMBER(3,0), 
	"REF_R" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REUNION
--------------------------------------------------------

  CREATE TABLE "GECOLE"."REUNION" 
   (	"ID_REUNION" NUMBER(4,0), 
	"TITRE" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"CONTENU" LONG, 
	"RESULTAT" VARCHAR2(100 BYTE), 
	"DATE_REUNION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SALLE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."SALLE" 
   (	"ID_SALLE" NUMBER(2,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"CAPACITE" NUMBER(2,0), 
	"DATE_CONSTRUCTION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SEANCE
--------------------------------------------------------

  CREATE TABLE "GECOLE"."SEANCE" 
   (	"ID_SEANCE" NUMBER, 
	"HEURE" NUMBER(1,0), 
	"JOUR" NUMBER(1,0), 
	"REF_INST" NUMBER, 
	"REF_MAT" NUMBER, 
	"REF_SALLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_ABS
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_ABS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_APPR
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_APPR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_C
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_C"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_E
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_E"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_INST
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_INST"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_MAT
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_MAT"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_MODULE
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_MODULE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_N
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_N"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_P
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_P"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_R
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_R"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_SALLE
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_SALLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_SC
--------------------------------------------------------

   CREATE SEQUENCE  "GECOLE"."SEQ_ID_SC"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into GECOLE.ABSENCE
SET DEFINE OFF;
REM INSERTING into GECOLE.APPARTIENT
SET DEFINE OFF;
REM INSERTING into GECOLE.APPRECIATION
SET DEFINE OFF;
REM INSERTING into GECOLE.CLASSE
SET DEFINE OFF;
REM INSERTING into GECOLE.ELEVE
SET DEFINE OFF;
REM INSERTING into GECOLE.INST
SET DEFINE OFF;
REM INSERTING into GECOLE.MATIERE
SET DEFINE OFF;
REM INSERTING into GECOLE.MODULE
SET DEFINE OFF;
REM INSERTING into GECOLE.NIVEAU
SET DEFINE OFF;
REM INSERTING into GECOLE.NOTE
SET DEFINE OFF;
REM INSERTING into GECOLE.PARENT
SET DEFINE OFF;
REM INSERTING into GECOLE.PARTICIPE
SET DEFINE OFF;
REM INSERTING into GECOLE.REUNION
SET DEFINE OFF;
REM INSERTING into GECOLE.SALLE
SET DEFINE OFF;
REM INSERTING into GECOLE.SEANCE
SET DEFINE OFF;
